language: php
sudo: false

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer update

script:
  - ./vendor/bin/phpunit;
  - ./vendor/bin/phpunit;
